apiVersion: v1
kind: Template
labels:
  template: ${NAME}
  builtFrom: ${BUILT_FROM}
metadata:
  name: ${NAME}-template
objects:

# ---------------------------------------------------------
# IMAGE STREAM
# ---------------------------------------------------------
- apiVersion: v1
  kind: ImageStream
  metadata:
    namespace: ${IMAGE_STREAM_NAMESPACE}
    name: ${IMAGE_STREAM}
  spec: {}

# ---------------------------------------------------------
# BUILD CONFIG
# ---------------------------------------------------------
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds the application image.
    name: ${NAME}${BUILD_SUFFIX}
  spec:
    output:
      to:
        kind: ImageStreamTag
        namespace: ${IMAGE_STREAM_NAMESPACE}
        name: ${IMAGE_STREAM}:${IMAGE_STREAM_TAG}
    resources:
      limits:
        memory: ${BUILD_MEMORY_LIMIT}
    source:
      type: Source
    strategy:
      sourceStrategy:
        from:
          kind: "ImageStreamTag"
          namespace: ${S2I_NAMESPACE}
          name: ${S2I}:latest
        incremental: true

# ---------------------------------------------------------
# PARAMETERS
# ---------------------------------------------------------
parameters:
- name: NAME
  displayName: Application Name
  description: Name of the application to build
  required: true

- name: S2I_NAMESPACE
  displayName: S2I Namespace
  description: Namespace containing the S2I Image
  required: true
  value: ci

- name: S2I
  displayName: S2I Image
  description: Name of the S2I Image to use
  required: true

- name: IMAGE_STREAM_NAMESPACE
  displayName: ImageStream Namespace
  description: Project that images should be published to
  required: true
  value: ci

- name: IMAGE_STREAM
  displayName: ImageStream
  description: ImageStream to create for images produced by this build
  required: true

- name: IMAGE_STREAM_TAG
  displayName: Image Tag
  description: Tag to use for the generated image
  required: true
  value: latest

- name: BUILD_SUFFIX
  displayName: Build Suffix
  description: Suffix to use for the build name
  value:

- name: BUILD_MEMORY_LIMIT
  displayName: Build Memory Limit
  description: Memory limit for OpenShift build
  required: true
  value: '1Gi'

- name: BUILT_FROM
  displayName: Built From
  description: Build type ('pullRequest', 'master', 'branch')
  required: true
  value: master
