loglevel: 'INFO'
job:
  throttle: 1
  options:
    logRotator:
      artifactDaysToKeepStr: ''
      artifactNumToKeepStr: '3'
      daysToKeepStr: ''
      numToKeepStr: '3'
    timeout:
      time: 1
      unit: 'HOURS'
config:
  build:
    buildEnvironment: 'dev'
  pr:
    buildEnabled: 1
    deployEnabled: 0
    buildEnvironment: 'dev'
  environments:
    # Generic Environment
    generic:
      appNamePrefix: ''
      appNamePostfix: ''
      dockerFile: 'Dockerfile'

      agent:
        name: 's_micro'
        label: 'jnlp'
        cloud: 'kubernetes'
        defaultContainer: 'jenkins-builder'
      container:
        builderAgentBase: 'base+jenkins_builder'
        buildingTool: 'img'
      
      gitUrl: 'https://github.com'
      gitSpace: 'TBD'
      gitCredentials: 'github.main.cicd.api.credentials' # Also used in library!!
      registryType: 'imagestream'
      registryUrl: 'docker-registry.default.svc:5000'
      registryUrlLogin: 'registry.pro-eu-west-1.openshift.com' # OpenShift ImageStream only
      registrySpace: 'ci'
      registryCredentials: 'registry.company.cicd.api.credentials'

      repository: 'Not used'
      repositoryUrl: 'Not used'
      repositoryCredentials: 'Not used'

    # Specific Environment
    dev:
      key: 'dev'
      name: 'Development'
      platformName: 'OpenShift Online Sandbox'
      platformOwner: 'company'
      platformNamespace: 'wltp-sandbox'
    test:
      key: 'test'
      name: 'Test'
      platformName: 'OpenShift Online PROD'
      platformOwner: 'company'
      platformNamespace: 'wltp'
    int:
      key: 'int'
      name: 'Integration'
      platformName: 'OpenShift on-prem INT (Staging/PreProd)'
      platformOwner: 'client'
      platformNamespace: 'wltpsimulation-int-int'

      gitUrl: 'https://git.client.com'
      gitSpace: 'TBD'
      gitCredentials: 'github.client.cicd.api.credentials'
      registryType: 'docker'
      registryUrl: 'reg-dhc.app.corpintra.net'
      registrySpace: 'company-insights'
      registryCredentials: 'registry.client.wins.cicd.api.credentials'
    prod:
      key: 'prod'
      name: 'Production'
      platformName: 'OpenShift on-prem PROD'
      platformOwner: 'client'
      platformNamespace: 'wltpsimulation-prod-prod'

      gitUrl: 'https://git.client.com'
      gitSpace: 'TBD'
      gitCredentials: 'github.client.cicd.api.credentials'
      registryType: 'docker'
      registryUrl: 'reg-dhc.app.corpintra.net'
      registrySpace: 'company-insights'
      registryCredentials: 'registry.client.wins.cicd.api.credentials'
    
    # Application Environment (same structure as above)
    app:
      
    # WLTP Insights
      wins:
        generic:
          appNamePrefix: 'wins-'
          appNamePostfix: ''
        dev:
          key: 'dev'
        test:
          key: 'test'
        int:
          key: 'int'
        prod:
          key: 'prod'

      # MaxSA
      maxsa:
        generic:
          appNamePrefix: 'maxsa-'
          appNamePostfix: ''
        dev:
          key: 'dev'
        test:
          key: 'test'
        int:
          key: 'int'
        prod:
          key: 'prod'
        